ALTER TABLE nodes ADD COLUMN IF NOT EXISTS log_paths TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS log_journalctl_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS log_retention_days INTEGER NOT NULL DEFAULT 0;
