BEGIN;

-- 000055_rpo_rto_gfs.up.sql
-- Policy: RPO/RTO 目标 + GFS 多级保留
-- Report: RPO/RTO 实际值 + 达标标记

ALTER TABLE policies ADD COLUMN IF NOT EXISTS rpo_minutes     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE policies ADD COLUMN IF NOT EXISTS rto_minutes     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE policies ADD COLUMN IF NOT EXISTS retention_mode  VARCHAR(16) NOT NULL DEFAULT 'simple';
ALTER TABLE policies ADD COLUMN IF NOT EXISTS keep_daily      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE policies ADD COLUMN IF NOT EXISTS keep_weekly     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE policies ADD COLUMN IF NOT EXISTS keep_monthly    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE policies ADD COLUMN IF NOT EXISTS keep_yearly     INTEGER NOT NULL DEFAULT 0;

ALTER TABLE reports ADD COLUMN IF NOT EXISTS actual_rpo_minutes INTEGER;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS actual_rto_minutes INTEGER;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS rpo_compliant       BOOLEAN;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS rto_compliant       BOOLEAN;

COMMIT;
