ALTER TABLE users ADD COLUMN totp_secret VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN totp_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN recovery_codes TEXT NOT NULL DEFAULT '';
