ALTER TABLE policies ADD COLUMN pre_hook TEXT NOT NULL DEFAULT '';
ALTER TABLE policies ADD COLUMN post_hook TEXT NOT NULL DEFAULT '';
ALTER TABLE policies ADD COLUMN hook_timeout_seconds INTEGER NOT NULL DEFAULT 300;
